package fusion

const vmx = `
.encoding = "UTF-8"
config.version = "8"
displayName = "{{.VM}}"
ethernet0.addressType = "static"
ethernet0.address = "{{.MAC1}}"
ethernet0.connectionType = "nat"
ethernet0.linkStatePropagation.enable = "TRUE"
ethernet0.present = "TRUE"
ethernet0.virtualDev = "e1000"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet1.addressType = "generated"
ethernet1.connectionType = "hostonly"
ethernet1.linkStatePropagation.enable = "TRUE"
ethernet1.present = "TRUE"
ethernet1.virtualDev = "e1000"
ethernet1.wakeOnPcktRcv = "FALSE"
floppy0.present = "FALSE"
guestOS = "other26xlinux-64"
hpet0.present = "TRUE"
ide1:0.deviceType = "cdrom-image"
ide1:0.fileName = "{{.ISO}}"
ide1:0.present = "TRUE"
mem.hotadd = "TRUE"
memsize = "{{.Memory}}"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.reset = "soft"
powerType.suspend = "soft"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsilogic"
scsi0:0.fileName = "{{.VM}}.vmdk"
scsi0:0.present = "TRUE"
virtualHW.productCompatibility = "hosted"
virtualHW.version = "10"
`
